// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.dfci.cccb.gameon.domain;

import edu.dfci.cccb.gameon.domain.Snp;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

privileged aspect Snp_Roo_Jpa_Entity {
    
    declare @type: Snp: @Entity;
    
    declare @type: Snp: @Table(schema = "PUBLIC", name = "SNP");
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "ID")
    private Long Snp.id;
    
    public Long Snp.getId() {
        return this.id;
    }
    
    public void Snp.setId(Long id) {
        this.id = id;
    }
    
}
