// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.dfci.cccb.gameon.domain;

import edu.dfci.cccb.gameon.domain.Snp;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Snp_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager Snp.entityManager;
    
    public static final EntityManager Snp.entityManager() {
        EntityManager em = new Snp().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Snp.countSnps() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Snp o", Long.class).getSingleResult();
    }
    
    public static List<Snp> Snp.findAllSnps() {
        return entityManager().createQuery("SELECT o FROM Snp o", Snp.class).getResultList();
    }
    
    public static Snp Snp.findSnp(Long id) {
        if (id == null) return null;
        return entityManager().find(Snp.class, id);
    }
    
    public static List<Snp> Snp.findSnpEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Snp o", Snp.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void Snp.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Snp.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Snp attached = Snp.findSnp(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Snp.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void Snp.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public Snp Snp.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Snp merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
