// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.dfci.cccb.gameon.domain;

import edu.dfci.cccb.gameon.domain.Snp;
import javax.persistence.Column;

privileged aspect Snp_Roo_DbManaged {
    
    @Column(name = "BETAVALUE")
    private Double Snp.betavalue;
    
    @Column(name = "BUILD", length = 255)
    private String Snp.build;
    
    @Column(name = "CHROMOSOME", length = 255)
    private String Snp.chromosome;
    
    @Column(name = "COORDINATE")
    private Long Snp.coordinate;
    
    @Column(name = "EAF_UK_VALUE")
    private Double Snp.eafUkValue;
    
    @Column(name = "EFFECT_ALLELE", length = 255)
    private String Snp.effectAllele;
    
    @Column(name = "L_CI_VALUE")
    private Double Snp.lCiValue;
    
    @Column(name = "MARKER_NAME", length = 255)
    private String Snp.markerName;
    
    @Column(name = "N_STUDY", length = 255)
    private String Snp.nStudy;
    
    @Column(name = "OR_VALUE")
    private Double Snp.orValue;
    
    @Column(name = "P_VALUE")
    private Double Snp.pValue;
    
    @Column(name = "REF_ALLELE", length = 255)
    private String Snp.refAllele;
    
    @Column(name = "RS_NUMBER", length = 255)
    private String Snp.rsNumber;
    
    @Column(name = "SE_VALUE")
    private Double Snp.seValue;
    
    @Column(name = "STRAND", length = 255)
    private String Snp.strand;
    
    @Column(name = "U_CI_VALUE")
    private Double Snp.uCiValue;
    
    @Column(name = "GENE_SYMBOL", length = 255)
    private String Snp.geneSymbol;
    
    @Column(name = "GENE_INFO", length = 255)
    private String Snp.geneInfo;
    
    @Column(name = "N_STUDY_ERNEG", length = 255)
    private String Snp.nStudyErneg;
    
    @Column(name = "EFFECT_ALLELE_ERNEG", length = 255)
    private String Snp.effectAlleleErneg;
    
    @Column(name = "REF_ALLELE_ERNEG", length = 255)
    private String Snp.refAlleleErneg;
    
    @Column(name = "BETAVALUE_ERNEG")
    private Double Snp.betavalueErneg;
    
    @Column(name = "SE_VALUE_ERNEG")
    private Double Snp.seValueErneg;
    
    @Column(name = "OR_VALUE_ERNEG")
    private Double Snp.orValueErneg;
    
    @Column(name = "L_CI_VALUE_ERNEG")
    private Double Snp.lCiValueErneg;
    
    @Column(name = "U_CI_VALUE_ERNEG")
    private Double Snp.uCiValueErneg;
    
    @Column(name = "P_VALUE_ERNEG")
    private Double Snp.pValueErneg;
    
    public Double Snp.getBetavalue() {
        return betavalue;
    }
    
    public void Snp.setBetavalue(Double betavalue) {
        this.betavalue = betavalue;
    }
    
    public String Snp.getBuild() {
        return build;
    }
    
    public void Snp.setBuild(String build) {
        this.build = build;
    }
    
    public String Snp.getChromosome() {
        return chromosome;
    }
    
    public void Snp.setChromosome(String chromosome) {
        this.chromosome = chromosome;
    }
    
    public Long Snp.getCoordinate() {
        return coordinate;
    }
    
    public void Snp.setCoordinate(Long coordinate) {
        this.coordinate = coordinate;
    }
    
    public Double Snp.getEafUkValue() {
        return eafUkValue;
    }
    
    public void Snp.setEafUkValue(Double eafUkValue) {
        this.eafUkValue = eafUkValue;
    }
    
    public String Snp.getEffectAllele() {
        return effectAllele;
    }
    
    public void Snp.setEffectAllele(String effectAllele) {
        this.effectAllele = effectAllele;
    }
    
    public Double Snp.getLCiValue() {
        return lCiValue;
    }
    
    public void Snp.setLCiValue(Double lCiValue) {
        this.lCiValue = lCiValue;
    }
    
    public String Snp.getMarkerName() {
        return markerName;
    }
    
    public void Snp.setMarkerName(String markerName) {
        this.markerName = markerName;
    }
    
    public String Snp.getNStudy() {
        return nStudy;
    }
    
    public void Snp.setNStudy(String nStudy) {
        this.nStudy = nStudy;
    }
    
    public Double Snp.getOrValue() {
        return orValue;
    }
    
    public void Snp.setOrValue(Double orValue) {
        this.orValue = orValue;
    }
    
    public Double Snp.getPValue() {
        return pValue;
    }
    
    public void Snp.setPValue(Double pValue) {
        this.pValue = pValue;
    }
    
    public String Snp.getRefAllele() {
        return refAllele;
    }
    
    public void Snp.setRefAllele(String refAllele) {
        this.refAllele = refAllele;
    }
    
    public String Snp.getRsNumber() {
        return rsNumber;
    }
    
    public void Snp.setRsNumber(String rsNumber) {
        this.rsNumber = rsNumber;
    }
    
    public Double Snp.getSeValue() {
        return seValue;
    }
    
    public void Snp.setSeValue(Double seValue) {
        this.seValue = seValue;
    }
    
    public String Snp.getStrand() {
        return strand;
    }
    
    public void Snp.setStrand(String strand) {
        this.strand = strand;
    }
    
    public Double Snp.getUCiValue() {
        return uCiValue;
    }
    
    public void Snp.setUCiValue(Double uCiValue) {
        this.uCiValue = uCiValue;
    }
    
    public String Snp.getGeneSymbol() {
        return geneSymbol;
    }
    
    public void Snp.setGeneSymbol(String geneSymbol) {
        this.geneSymbol = geneSymbol;
    }
    
    public String Snp.getGeneInfo() {
        return geneInfo;
    }
    
    public void Snp.setGeneInfo(String geneInfo) {
        this.geneInfo = geneInfo;
    }
    
    public String Snp.getNStudyErneg() {
        return nStudyErneg;
    }
    
    public void Snp.setNStudyErneg(String nStudyErneg) {
        this.nStudyErneg = nStudyErneg;
    }
    
    public String Snp.getEffectAlleleErneg() {
        return effectAlleleErneg;
    }
    
    public void Snp.setEffectAlleleErneg(String effectAlleleErneg) {
        this.effectAlleleErneg = effectAlleleErneg;
    }
    
    public String Snp.getRefAlleleErneg() {
        return refAlleleErneg;
    }
    
    public void Snp.setRefAlleleErneg(String refAlleleErneg) {
        this.refAlleleErneg = refAlleleErneg;
    }
    
    public Double Snp.getBetavalueErneg() {
        return betavalueErneg;
    }
    
    public void Snp.setBetavalueErneg(Double betavalueErneg) {
        this.betavalueErneg = betavalueErneg;
    }
    
    public Double Snp.getSeValueErneg() {
        return seValueErneg;
    }
    
    public void Snp.setSeValueErneg(Double seValueErneg) {
        this.seValueErneg = seValueErneg;
    }
    
    public Double Snp.getOrValueErneg() {
        return orValueErneg;
    }
    
    public void Snp.setOrValueErneg(Double orValueErneg) {
        this.orValueErneg = orValueErneg;
    }
    
    public Double Snp.getLCiValueErneg() {
        return lCiValueErneg;
    }
    
    public void Snp.setLCiValueErneg(Double lCiValueErneg) {
        this.lCiValueErneg = lCiValueErneg;
    }
    
    public Double Snp.getUCiValueErneg() {
        return uCiValueErneg;
    }
    
    public void Snp.setUCiValueErneg(Double uCiValueErneg) {
        this.uCiValueErneg = uCiValueErneg;
    }
    
    public Double Snp.getPValueErneg() {
        return pValueErneg;
    }
    
    public void Snp.setPValueErneg(Double pValueErneg) {
        this.pValueErneg = pValueErneg;
    }
    
}
