// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.dfci.cccb.gameon.domain;

import edu.dfci.cccb.gameon.domain.Snp;
import javax.persistence.Column;

privileged aspect Snp_Roo_DbManaged {
    
    @Column(name = "BETAVALUE")
    private Double Snp.betavalue;
    
    @Column(name = "BUILD", length = 255)
    private String Snp.build;
    
    @Column(name = "CHROMOSOME", length = 255)
    private String Snp.chromosome;
    
    @Column(name = "COORDINATE")
    private Long Snp.coordinate;
    
    @Column(name = "EAF_UK_VALUE")
    private Double Snp.eafUkValue;
    
    @Column(name = "EFFECT_ALLELE", length = 255)
    private String Snp.effectAllele;
    
    @Column(name = "L_CI_VALUE")
    private Double Snp.lCiValue;
    
    @Column(name = "MARKER_NAME", length = 255)
    private String Snp.markerName;
    
    @Column(name = "N_STUDY", length = 255)
    private String Snp.nStudy;
    
    @Column(name = "OR_VALUE")
    private Double Snp.orValue;
    
    @Column(name = "P_VALUE")
    private Double Snp.pValue;
    
    @Column(name = "REF_ALLELE", length = 255)
    private String Snp.refAllele;
    
    @Column(name = "RS_NUMBER", length = 255)
    private String Snp.rsNumber;
    
    @Column(name = "SE_VALUE")
    private Double Snp.seValue;
    
    @Column(name = "STRAND", length = 255)
    private String Snp.strand;
    
    @Column(name = "GENE_INFO", length = 255)
    private String Snp.geneInfo;
    
    @Column(name = "U_CI_VALUE")
    private Double Snp.uCiValue;
    
    public Double Snp.getBetavalue() {
        return betavalue;
    }
    
    public void Snp.setBetavalue(Double betavalue) {
        this.betavalue = betavalue;
    }
    
    public String Snp.getBuild() {
        return build;
    }
    
    public void Snp.setBuild(String build) {
        this.build = build;
    }
    
    public String Snp.getChromosome() {
        return chromosome;
    }
    
    public void Snp.setChromosome(String chromosome) {
        this.chromosome = chromosome;
    }
    
    public Long Snp.getCoordinate() {
        return coordinate;
    }
    
    public void Snp.setCoordinate(Long coordinate) {
        this.coordinate = coordinate;
    }
    
    public Double Snp.getEafUkValue() {
        return eafUkValue;
    }
    
    public void Snp.setEafUkValue(Double eafUkValue) {
        this.eafUkValue = eafUkValue;
    }
    
    public String Snp.getEffectAllele() {
        return effectAllele;
    }
    
    public void Snp.setEffectAllele(String effectAllele) {
        this.effectAllele = effectAllele;
    }
    
    public Double Snp.getLCiValue() {
        return lCiValue;
    }
    
    public void Snp.setLCiValue(Double lCiValue) {
        this.lCiValue = lCiValue;
    }
    
    public String Snp.getMarkerName() {
        return markerName;
    }
    
    public void Snp.setMarkerName(String markerName) {
        this.markerName = markerName;
    }
    
    public String Snp.getNStudy() {
        return nStudy;
    }
    
    public void Snp.setNStudy(String nStudy) {
        this.nStudy = nStudy;
    }
    
    public Double Snp.getOrValue() {
        return orValue;
    }
    
    public void Snp.setOrValue(Double orValue) {
        this.orValue = orValue;
    }
    
    public Double Snp.getPValue() {
        return pValue;
    }
    
    public void Snp.setPValue(Double pValue) {
        this.pValue = pValue;
    }
    
    public String Snp.getRefAllele() {
        return refAllele;
    }
    
    public void Snp.setRefAllele(String refAllele) {
        this.refAllele = refAllele;
    }
    
    public String Snp.getRsNumber() {
        return rsNumber;
    }
    
    public void Snp.setRsNumber(String rsNumber) {
        this.rsNumber = rsNumber;
    }
    
    public Double Snp.getSeValue() {
        return seValue;
    }
    
    public void Snp.setSeValue(Double seValue) {
        this.seValue = seValue;
    }
    
    public String Snp.getStrand() {
        return strand;
    }
    
    public void Snp.setStrand(String strand) {
        this.strand = strand;
    }
    
    public String Snp.getGeneInfo() {
        return geneInfo;
    }
    
    public void Snp.setGeneInfo(String geneInfo) {
        this.geneInfo = geneInfo;
    }
    
    public Double Snp.getUCiValue() {
        return uCiValue;
    }
    
    public void Snp.setUCiValue(Double uCiValue) {
        this.uCiValue = uCiValue;
    }
    
}
