// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.dfci.cccb.gameon.domain;

import edu.dfci.cccb.gameon.domain.Snp;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Snp_Roo_Configurable {
    
    declare @type: Snp: @Configurable;
    
}
