// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.dfci.cccb.gameon.web;

import edu.dfci.cccb.gameon.domain.Snp;
import edu.dfci.cccb.gameon.web.SnpController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect SnpController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String SnpController.create(@Valid Snp snp, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, snp);
            return "snps/create";
        }
        uiModel.asMap().clear();
        snp.persist();
        return "redirect:/snps/" + encodeUrlPathSegment(snp.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String SnpController.createForm(Model uiModel) {
        populateEditForm(uiModel, new Snp());
        return "snps/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String SnpController.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("snp", Snp.findSnp(id));
        uiModel.addAttribute("itemId", id);
        return "snps/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String SnpController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("snps", Snp.findSnpEntries(firstResult, sizeNo));
            float nrOfPages = (float) Snp.countSnps() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("snps", Snp.findAllSnps());
        }
        return "snps/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String SnpController.update(@Valid Snp snp, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, snp);
            return "snps/update";
        }
        uiModel.asMap().clear();
        snp.merge();
        return "redirect:/snps/" + encodeUrlPathSegment(snp.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String SnpController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, Snp.findSnp(id));
        return "snps/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String SnpController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        Snp snp = Snp.findSnp(id);
        snp.remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/snps";
    }
    
    void SnpController.populateEditForm(Model uiModel, Snp snp) {
        uiModel.addAttribute("snp", snp);
    }
    
    String SnpController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
